//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.19 at 12:13:05 PM CST 
//


package study.packetFormat.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for msgContent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="msgContent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userMebCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reimbersementList" type="{https://mobile.99bill.com/payment}reimbersementList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "msgContent", propOrder = {
    "password",
    "userMebCode",
    "reimbersementList"
})
public class MsgContent implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@XmlElement(required = true)
    protected String password;
    @XmlElement(required = true)
    protected String userMebCode;
    @XmlElement(required = true)
    protected ReimbersementList reimbersementList;

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the userMebCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserMebCode() {
        return userMebCode;
    }

    /**
     * Sets the value of the userMebCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserMebCode(String value) {
        this.userMebCode = value;
    }

    /**
     * Gets the value of the reimbersementList property.
     * 
     * @return
     *     possible object is
     *     {@link ReimbersementList }
     *     
     */
    public ReimbersementList getReimbersementList() {
        return reimbersementList;
    }

    /**
     * Sets the value of the reimbersementList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReimbersementList }
     *     
     */
    public void setReimbersementList(ReimbersementList value) {
        this.reimbersementList = value;
    }

}
