//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.19 at 12:13:05 PM CST 
//


package study.packetFormat.model.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the study.packetFormat.model.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory implements java.io.Serializable {


    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: study.packetFormat.model.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link MsgContent }
     * 
     */
    public MsgContent createMsgContent() {
        return new MsgContent();
    }

    /**
     * Create an instance of {@link ReimbersementList }
     * 
     */
    public ReimbersementList createReimbersementList() {
        return new ReimbersementList();
    }

    /**
     * Create an instance of {@link Reimbersement }
     * 
     */
    public Reimbersement createReimbersement() {
        return new Reimbersement();
    }

    /**
     * Create an instance of {@link DeviceInfo }
     * 
     */
    public DeviceInfo createDeviceInfo() {
        return new DeviceInfo();
    }

}
