//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.19 at 12:13:05 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://mobile.99bill.com/payment", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package study.packetFormat.model.xml;
