//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.19 at 12:13:05 PM CST 
//


package study.packetFormat.model.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reimbersementList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reimbersementList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reimbersement" type="{https://mobile.99bill.com/payment}reimbersement" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reimbersementList", propOrder = {
    "reimbersement"
})
public class ReimbersementList implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 5315462091828469730L;
	protected List<Reimbersement> reimbersement;

    /**
     * Gets the value of the reimbersement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reimbersement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReimbersement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reimbersement }
     * 
     * 
     */
    public List<Reimbersement> getReimbersement() {
        if (reimbersement == null) {
            reimbersement = new ArrayList<Reimbersement>();
        }
        return this.reimbersement;
    }

}
