//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.19 at 12:13:05 PM CST 
//


package study.packetFormat.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reimbersement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reimbersement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="creditBankId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="creditBankName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="creditCardNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requestDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reimbersement", propOrder = {
    "creditBankId",
    "creditBankName",
    "creditCardNo",
    "amount",
    "requestDate",
    "status"
})
public class Reimbersement implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -7639343611012767244L;
	@XmlElement(required = true)
    protected String creditBankId;
    @XmlElement(required = true)
    protected String creditBankName;
    @XmlElement(required = true)
    protected String creditCardNo;
    @XmlElement(required = true)
    protected String amount;
    @XmlElement(required = true)
    protected String requestDate;
    @XmlElement(required = true)
    protected String status;

    /**
     * Gets the value of the creditBankId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditBankId() {
        return creditBankId;
    }

    /**
     * Sets the value of the creditBankId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditBankId(String value) {
        this.creditBankId = value;
    }

    /**
     * Gets the value of the creditBankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditBankName() {
        return creditBankName;
    }

    /**
     * Sets the value of the creditBankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditBankName(String value) {
        this.creditBankName = value;
    }

    /**
     * Gets the value of the creditCardNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditCardNo() {
        return creditCardNo;
    }

    /**
     * Sets the value of the creditCardNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditCardNo(String value) {
        this.creditCardNo = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the requestDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestDate() {
        return requestDate;
    }

    /**
     * Sets the value of the requestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestDate(String value) {
        this.requestDate = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
